# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.

# built-in
#env = GDK_SCALE,1
monitor=eDP-1, preferred, auto, 1
#monitor=eDP-1, disable

#Good compromise for 27" or 32" 4K monitors (but fractional!)
#env = GDK_SCALE,1.75
#monitor=,preferred,0x0,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
#env = GDK_SCALE,1
monitor=,preferred,auto,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2

# custom

# Home monitor 27" 4K
env = GDK_SCALE,1
monitor = desc:Lenovo Group Limited LEN T27p-10 0x3148545A, 3840x2160@30, auto, 2
# aro aarhus
monitor=desc:Samsung Electric Company LS32A80 HK7X100567,3840x2160@30, auto, 2


# turn off built-in on lid close and vice versa
bindl=,switch:off:Lid Switch,exec,~/.local/bin/check_clamshell open
bindl=,switch:on:Lid Switch,exec,~/.local/bin/check_clamshell close

# LC meeting rooms
monitor = desc:VCS Yealink, preffered, auto, 2
